spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dronedb
    username: root
    password: tochukwu
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8082
